// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var rerun;
    rerun = function(t, f) {
      return setInterval(f, t);
    };
    return rerun(1000, function() {
      $('input').swap($('input').val() + "1");
      $('textarea').swap($('textarea').val() + "2");
      return $('.editable').swap($('.editable').text() + "3");
    });
  });

}).call(this);
